
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbrgkzijdovhkoklmoei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicmdremlqZG92aGtva2xtb2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjMyNDksImV4cCI6MjA1OTU5OTI0OX0.GBEzIR5bw66noBmeQ2YWJQt9_h6vOHiBqnFdaV36tn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
