
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbrgkzijdovhkoklmoei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicmdremlqZG92aGtva2xtb2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjMyNDksImV4cCI6MjA1OTU5OTI0OX0.GBEzIR5bw66noBmeQ2YWJQt9_h6vOHiBqnFdaV36tn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      debug: true // Enable debug mode to help troubleshoot authentication issues
    }
  }
);

// Debug helper to check authentication status
export const checkAuthStatus = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    console.log("Current auth status:", error ? "Error" : "OK", 
      "Session:", data.session ? "Exists" : "None", 
      error || "");
    return data;
  } catch (e) {
    console.error("Failed to check auth status:", e);
    return { session: null };
  }
};
